apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: docker-hub-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.docker.secrets.name }}
        property: dockerconfigjson
